[package]
name = "goxlr-ipc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxlr-types = { path = "../types", features = ["serde", "enumset"] }
serde = { version = "1.0", features = ["derive"] }
tokio = {version = "1.0", features = ["net"]}
tokio-util = { version = "0.6.9", features=["codec"]}
tokio-serde = { version = "0.8.0", features=["bincode"] }
futures = "0.3.19"
strum = { version = "0.23"}
enumset = "1.0.8"